image: python:3.11-slim-bookworm
    
pages:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install -y cmake build-essential
    - pip install --no-cache-dir -U sphinx furo numpy vf3py
    - sphinx-build -b html ./docs public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

build_test:
  stage: test
  script:
    - apt-get update -y
    - apt-get install -y cmake build-essential
    - pip install conan
    - conan profile detect
    - cd release_assemble
    - python release_assemble.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
